---

- name: Deploy Nexus 2
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/tools.yml

  tasks:
    - set_fact:
        ocp_project: "{{ project_tools }}"
        ocp_project_display_name: "{{ project_tools_display_name }}"
        ocp_project_desc: "{{ project_tools_desc }}"
        work_dir_name: nexus2
        resources_dir: "{{ resources_home_dir }}/nexus2"
        uninstall_delete_project: False        
    - include_role:
        name: ../roles/openshift_nexus2
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_nexus2
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"